#!/usr/bin/env python
import argparse
import topology
import switch
from sys import argv
from mininet.node import CPULimitedHost
from mininet.net import Mininet
from mininet.log import setLogLevel, info
from mininet.node import OVSSwitch, UserSwitch, OVSLegacyKernelSwitch, RemoteController
from mininet.cli import CLI

def run():
    # Parse arguments and store them
    parser = argparse.ArgumentParser()
    # parser.add_argument('--console', action='store_true')
    # parser.add_argument('--start', action='store_true')
    # parser.add_argument('--stop', action='store_true')
    parser.add_argument('-c', '--controller', action='append', type=str)
    parser.add_argument('-a', '--topo-arg', action='append', type=int)

    parser.add_argument('-t', '--topo', nargs='?', const="SwitchTopo", type=str,
                        help='LinearTopo, SwitchTopo, SingleSwitchTopo, SingleSwitchReversedTopo, TreeTopo (default: SwitchTopo)')

    parser.add_argument('-s', '--switch', nargs='?', const="OVSSwitch", type=str,
                        help='OVSSwitch, UserSwitch, OVSLegacyKernelSwitch (default: OVSSwitch)')
    a = parser.parse_args()

    # If no arguments passed, set the default values
    if a.controller == None: a.controller = [ "127.0.0.1" ]
    if a.topo_arg == None: a.topo_arg = [ 1 ]
    if a.topo == None: a.topo = "SwitchTopo"
    if a.switch == None: a.switch = "OVSSwitch"

    # Create topology
    cur_topo = getattr(topology, a.topo)(*a.topo_arg)

    # Get switch type
    cur_switch = getattr(switch, a.switch)

    # Create mininet
    net = Mininet(topo=cur_topo, switch=cur_switch, controller=None)

    # Create and add controllers
    for i, address in enumerate(a.controller):
        net.addController(RemoteController('c{0}'.format(i), address, 6653))

    # Start/stop mininet
    # if a.start:
    net.start()
    # if a.console:
    CLI(net)
    # if a.stop:
    net.stop()

if __name__ == '__main__':
    setLogLevel('info')
    run()
